### ISSUE TITLE
Failed to update ymcd

### ISSUE THREAD

**Issue by jacobdufault** [Qusic/atom-youcompleteme#16]
Hi,

I get an error whenever I install or enable this extension. I'm running linux; 0.4.0 would give me the "remove" is not a function error that it appears you fixed in 0.4.1.

```
Failed to update ymcd
Undefined is not a function
```

Let me know if there is more information I can provide. Thanks!

**Comment by jacobdufault** [comment]
Here is more error information:

```
Unhandled promise rejection Promise with error: Error: ENOENT: no such file or directory, open '~/.atom/packages/you-complete-me/ycmd/ycmd/default_settings.json'
```

**Comment by Qusic** [comment]
Can you provide the call stack of the first error?

**Comment by mrharicot** [comment]
Hi,

Same error here. Ubuntu 14.04 and atom 0.210.0.
Here is what I get if I run atom with -f:
[11018:0622/163723:INFO:CONSOLE(14)] "Unhandled promise rejection %o with error: %o", source: file:///usr/share/atom/resources/app.asar/static/index.js (14)

How can I get the call stack?

**Comment by Qusic** [comment]
0.4.2 should fix all of them. Please tell me if the issue persists.

**Comment by mrharicot** [comment]
Thanks! It now works.

I had to manually install clang-3.6 before compiling ycmd to avoid a hash mismatch error.
Also the last line from your usage code should be:
./build.py [--clang-completer] [--omnisharp-completer] [--gocode-completer]

**Comment by mrharicot** [comment]
The build works without any problem.
However the autocomplete does not seem to work for me. (wether it is automatic or when I hit ctrl-space)
Here is what I have if I run with -f:
[10276:0622/191931:INFO:CONSOLE(20)] "[YCM-ERROR]", source: /home/clement/.atom/packages/you-complete-me/lib/provider.coffee (20)

**Comment by jacobdufault** [comment]
I also got the hash mismatch, but rerunning the build command fixed/ignored the issue.

```
CMake Error at ycm/CMakeLists.txt:87 (file):
  file DOWNLOAD HASH mismatch

    for file: [/usr/local/google/home/jdufault/.atom/packages/you-complete-me/ycmd/cpp/../clang_archives/clang+llvm-3.6.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz]
      expected hash: ["e8396103fbf794e6af671593659458dfe841c32234d3cd4f37be0b48cd6a9f8b"]
        actual hash:  [e8396103fbf794e6af671593659458dfe841c32234d3cd4f37be0b48cd6a9f8b]
```

The hashes look identical to me, except the expected one is in quotes.

Completion works as expected, though I have a custom ycm_config.py.

Are there plans to support GoToDefinition?

Thanks!

**Comment by Qusic** [comment]
As for hash mismatch, it should be an issue of ycmd. I haven't pulled upstream changes for a while and I will see if it is fixed in upstream later.
Currently you can try the full installation guide of ycmd for now. It shouldn't be difficult.

Instead of running the install.py script, you:

1. Use cmake to generate makefiles
  mkdir anywhere you like and cd into it
  cmake -G "Unix Makefiles" -DPATH_TO_LLVM_ROOT=~/ycm_temp/llvm_root_dir . ~/.atom/packages/you-complete-me/ycmd/cpp

2. Run make to build them
  make ycm_support_libs

See here for more information: https://github.com/Valloric/YouCompleteMe#full-installation-guide

I have plans to support GoToDefinition. But I'm quite busy recently at school and will continue working on this project several weeks later.
